force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exchange_Rate__c/fields/Integration_Log__c.field-meta.xml
<CustomField>
    <fullName>Integration_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Log</label>
    <referenceTo>Integration_Log__c</referenceTo>
    <relationshipLabel>Exchange Rates</relationshipLabel>
    <relationshipName>Exchange_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateRates.cls
/**
 * Created by Leonid Bartenev
 */

public class Batch_UpdateRates implements Database.Batchable<Exchange_Rate__c>, Database.Stateful, Database.AllowsCallouts{
    
    public static final String UPDATE_RATES_JOB_NAME = 'UpdateExchangeRatesJob';
    public Integer intervalInMinutes;
    
    public Batch_UpdateRates(Integer intervalInMinutes){
        this.intervalInMinutes = intervalInMinutes;
    }
    
    public Iterable<Exchange_Rate__c> start(Database.BatchableContext bc){
        return new List<Exchange_Rate__c>{new Exchange_Rate__c()};
    }
    
    public void execute(Database.BatchableContext bc, List<Exchange_Rate__c> dummyRates){
        List<Exchange_Rate__c> rates = [SELECT Id, Currency__c FROM Exchange_Rate__c];
        RemoteCall_GetRates getRatesRemoteCall = new RemoteCall_GetRates();
        Map<String, Decimal> remoteRatesMap = new Map<String, Decimal>();
        try{
            RemoteCall_GetRates.RatesData ratesData = (RemoteCall_GetRates.RatesData) getRatesRemoteCall.execute();
            remoteRatesMap = ratesData.rates;
        }catch (Exception e){
            System.debug('ERROR: ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
        Map<String, Exchange_Rate__c> dbRatesMap = new Map<String, Exchange_Rate__c>();
        for(Exchange_Rate__c rate : rates) {
            dbRatesMap.put(rate.Currency__c, rate);
            if(getRatesRemoteCall.log != null) rate.Integration_Log__c = getRatesRemoteCall.log.Id;
        }
        List<Exchange_Rate__c> ratesForUpdate = new List<Exchange_Rate__c>();
        for(String remoteRateKey : remoteRatesMap.keySet()){
            Exchange_Rate__c dbRate = dbRatesMap.get(remoteRateKey);
            if(dbRate == null) {
                dbRate = new Exchange_Rate__c(
                        Currency__c = remoteRateKey,
                        Integration_Log__c = getRatesRemoteCall.log.Id
                );
            }
            dbRate.Rate__c = remoteRatesMap.get(remoteRateKey);
            ratesForUpdate.add(dbRate);
        }
        upsert ratesForUpdate;
    }
    
    public void finish(Database.BatchableContext param1){
        System.scheduleBatch(new Batch_UpdateRates(intervalInMinutes), UPDATE_RATES_JOB_NAME, intervalInMinutes);

    }
    
    public static void run(Integer intervalInMinutes){
        stop();
        Database.executeBatch(new Batch_UpdateRates(intervalInMinutes));
    }
    
    public static void stop(){
        List<CronTrigger> cronTriggers = [
                SELECT Id
                FROM CronTrigger
                WHERE CronJobDetail.Name =: UPDATE_RATES_JOB_NAME
        ];
        if(!cronTriggers.isEmpty()) {
            for(CronTrigger cronT : cronTriggers) {
                System.abortJob(cronT.Id);
                System.debug('Process: ' + UPDATE_RATES_JOB_NAME + ' stopped');
            }
        }
    }

}